# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91687b98db8e91aae2483232abe7c325a0ce2ea66feb78d1f67a5185dbb63edf5ed6ecfb3fc41e8aea3dd8007aa725f496056e71057760d972303803f0928a93

test:
  secret_key_base: fc8c1de6ef3c70e07498cc92e8f27adc46e33859718caa9bd56d2a86db64d12ce6688ab86a5f2e675e6a0bdebc0c9329f2d92528e1121ee2916a6276cb20e268

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
